name: Build App and Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #  v2
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          #cache: maven
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Gradle config
        run: |
          jf gradlec \
            --repo-deploy=joepet-gradle-release-local \
            --repo-resolve=joepet-gradle-release
      - name: Gradke Build & Test
        run: |
          # Build steps here
          jf gradle clean build test

      # - name: Build Tag and push Docker Image
      #   env:
      #     IMAGE_NAME: joefrog.jfrog.io/petclinic-docker/petclinic-image:${{ github.run_number }}
      #   run: |
      #     jf docker build -t $IMAGE_NAME .
      #     jf docker push $IMAGE_NAME    